### ISSUE TITLE
Polka code block styling should respect light vs dark mode

### ISSUE THREAD

**Issue by jwhitley** [callumhackett/obsidian_polka_theme#11]
I'm running into some appearance issues with Polka and code blocks.  Namely, it's a bit jarring that code blocks don't default to matching the current Obsidian light vs dark mode. FWIW, I use "Adapt to system" where light and dark mode switch based on time of day... so this is literally a "recurring" problem. ;-) This also confuses the styling of other plugins such as Obsidian Numerals.  Here are some screenshots produced in a test vault with Polka, Style Settings, and Obsidian Numerals installed & enabled.  First, dark mode which appears as I'd expect:

<img width="1136" alt="Screenshot 2023-03-11 at 9 34 16 AM" src="https://user-images.githubusercontent.com/44155/224503257-ede18757-c449-4bdb-bada-6476f42329ad.png">

Now light mode. Numerals' background is dark, but its styling expects a light background in light mode, and so the effective contrast is about zero. Likewise, the dark code blocks feel jarring in an otherwise light field.

<img width="1136" alt="Screenshot 2023-03-11 at 9 34 24 AM" src="https://user-images.githubusercontent.com/44155/224503289-18fd6f8c-c2d6-4d21-82ae-be040be2d603.png">

Offhand, the simplest solution appears to be to split "Code Block Color Settings" under Style Settings > Polka into two settings, one each for light and dark modes.  Likewise, that would require that Polka's default code block theme have light and dark variants.

Sample Markdown for reference:
````
# Inline code blocks

This is a color test of `inline code blocks`, code in the middle of a span of text.

# Standalone code blocks

This is a test of standalone code blocks:
```
wow {
  much code;
}
so => monospace
```

# Obsidian Numerals test

```math
lets = 40
add = 20
things = 100
up = 2
lets + add + things + up =>
```
````

While I'm at it, Polka is amazing. I adore it, and it immediately stuck as my default Obsidian theme after Eleanor Konik tipped it off in her newsletter. Thanks for making and sharing it!

**Comment by callumhackett** [comment]
Thanks for the detailed comments, and I'm glad you're enjoying the theme besides the issues!

As you can tell from the default colors, my own preference is to view code against a dark background in both light and dark modes, but I can see that this perhaps shouldn't be the default setting.

There are parameters in Obsidian that plugin developers can use to prevent the text issues you describe if ever there's a dark code block in a light theme, but it seems there's a general expectation that light mode themes will have light code blocks, so those parameters are often overlooked.

I agree that the best solution will be to have a Style Settings option and I should be able to get around to a fix this weekend.

**Comment by jwhitley** [comment]
Thanks much for the pointer re: the text issues. I was able to dig in and figure out what was going on with Numerals specifically: it was mixing the use of `--text` and `--code` prefix colors for its math block styles. I [submitted a PR](https://github.com/gtg922r/obsidian-numerals/pull/35) over the weekend, now on `master`, which standardizes the math block theming to always use `--code` vars for consistency.

That said, I do still think separate dark vs light code block style choices would be a great addition to Polka.

**Comment by callumhackett** [comment]
That's very diligent of you, well done! As you can see, I was too busy to get a fix done over the weekend but it won't be long.
