### ISSUE TITLE
Franklin Gothic Book source?

### ISSUE THREAD

**Issue by jwhitley** [callumhackett/obsidian_polka_theme#12]
Hi! I've noted that Polka's default font, Franklin Gothic Book, looks good on my Mac but the default installation doesn't support heavier weights – so bold items essentially vanish.  Likewise, there isn't a default Franklin Gothic on my iPad. So it falls back (probably Helvetica Neue, but who knows since there's no mobile inspector), but does at least render bold properly.

So my question: are you aware of a good source for a Franklin Gothic font with multiple weights (or heck, is a variable font)... and maybe isn't a 400€ font set? I dropped Adobe CC a while back, so no longer have the Adobe Fonts lazy option.

**Comment by callumhackett** [comment]
Hi. I don't have a Mac, so this is useful to know. I had a look into free alternatives to Franklin Gothic at one point and the closest I could find was [Rubik](https://fonts.google.com/specimen/Rubik). It's by no means a replica - the differences are clear when they're viewed side by side - but many of the letter shapes and the overall effect are very similar, and I find both pleasing. Franklin Gothic's main advantage is that it's more readable for longer text but Rubik is good enough that I would use it without another alternative, and I haven't found any others yet.

**Comment by callumhackett** [comment]
Addendum: since this prompted me to have a second look, I think I would strongly recommend [Public Sans](https://fonts.google.com/specimen/Public+Sans). It is much better than Rubik as a direct replacement for Franklin Gothic, and it is also much better (in my opinion) than Libre Franklin, which is an open source variant of Franklin it's based on. I'm not aware of any free or cheap sources or distributions of an actual Franklin Gothic itself.

**Comment by jwhitley** [comment]
Thanks Callum! I did a fair bit of trying things and hunting around (starting with the fallbacks in Polka), but agreed: Public Sans seems like a wonderful option. I definitely prefer it over Rubik. It has both static and variable options to boot. Dropped it on my iPad (using Fontcase) yesterday and it looks great, will give it a go on the Mac today.
