### ISSUE TITLE
Polka dots are not showing on my obsidian?

### ISSUE THREAD

**Issue by UserPickles27** [callumhackett/obsidian_polka_theme#15]
I’m not sure why the polka dots aren’t showing I just downloaded this theme.  I even changed the accent color just to see if that did anything it didn’t. I messed around with settings to see if I could fix anything there but I had no luck. I also have the style settings plugin and I don’t have “remove polka dots” turned on either. I use obsidian on my iPad so I’m questioning if thats probably the reason why?

**Comment by callumhackett** [comment]
Thanks for the heads up. It looks like styling for the mobile apps works differently than I expected, so I've updated the theme with a fix that works at least on Android. Let me know if it works for you on the iPad too.

**Comment by UserPickles27** [comment]
Thank you so much!!! I have the polka dots I’m so happy!
