### ISSUE TITLE
Better support for File Tree Alternative Plugin

### ISSUE THREAD

**Issue by danieltomasz** [callumhackett/obsidian_polka_theme#3]
I really like the theme!
I observed one thing - the theme doesnt fully support File Tree Alternative in a light mode
https://github.com/ozntel/file-tree-alternative

<img width="316" alt="image" src="https://user-images.githubusercontent.com/7980381/219659867-b8180ebf-7655-4214-a121-493e82418319.png">

It seems that some colours are inherited from dark color scheme

<img width="319" alt="image" src="https://user-images.githubusercontent.com/7980381/219660053-d0f0a351-db03-4729-9a12-05173d9d1023.png">

**Comment by callumhackett** [comment]
Thanks for the appreciation and for bringing this to my attention. :)

I've just updated Polka to v1.2, which has various fixes and improvements, including new support for File Tree Alternative (you can update by going to the theme's page in the Obsidian theme manager). Let me know if I missed anything!

**Comment by danieltomasz** [comment]
Thanks, it  is flawless now ! :)
