### ISSUE TITLE
[feature request] manage color settings via style settings plugin

### ISSUE THREAD

**Issue by danieltomasz** [callumhackett/obsidian_polka_theme#4]
For future development direction - for users might be much easier to set colors via style settings, also for theme developers it  might allows to ship a few  predefined color  and theme settings (I like the current color variant :) ) 
https://github.com/mgmeyers/obsidian-style-settings

Example of minimal settings for theme
https://github.com/lnbgc/obsidian-jotter

**Comment by callumhackett** [comment]
Thanks for the suggestion. I'm glad that the theme no longer requires a CSS snippet to change the accent color but it would definitely be nice to make more customizations easier. I'll look into it. :)

**Comment by callumhackett** [comment]
Style Settings is now supported in v1.3.0. See the updated readme for examples of the new features, or experiment with the options!
