### ISSUE TITLE
Polka visually adds spacing between formatting symbols and text

### ISSUE THREAD

**Issue by FeralFlora** [callumhackett/obsidian_polka_theme#6]
First, thanks for a great looking theme!

The issue I've noticed is that Polka visually adds spacing around formatting symbols such as *, **, == and the words that they surround.

So, instead of `**strong words**` I see `** strong words **`. I don't know if this is intentional or not, but if it is, it would be nice if this could be toggled off in Style Settings.

Edit: Correction, this only occurs for highlight symbols (==).

**Comment by callumhackett** [comment]
Thanks for the feedback.

I've tried to reproduce this in live preview and source modes but I don't see this behaviour. Are there any prior steps to reproducing this, or is it possible that you have a conflict with a font or a plugin?

**Comment by FeralFlora** [comment]
>is it possible that you have a conflict with a font or a plugin?

It could be. But the reason I am implicating Polka is that when I switch back to my previous theme, the Github theme, then this behavior disappears and the spaces are not there anymore.

But I must add that I was mistaken before. This apparently only occurs for highlighted text using ==. Perhaps you can reproduce that? Sorry for the confusion.

**Comment by callumhackett** [comment]
Ah, thanks for the clarification. I was able to identify the problem and a fix is now available in v1.3.5. :)

**Comment by FeralFlora** [comment]
Thanks for the quick work, the fix works for me!
