### ISSUE TITLE
Compatibility issue with Plugin update tracker in light mode

### ISSUE THREAD

**Issue by FeralFlora** [callumhackett/obsidian_polka_theme#7]
There is an issue with dark text on a dark background on the Plugin updates page of the Plugin update tracker plugin. See the screenshot. Perhaps compatibility between Polka and this plugin could be added?
![image](https://user-images.githubusercontent.com/33608083/222403913-92b6dc0d-82a9-48aa-bc13-1736fe4d5e7e.png)

**Comment by callumhackett** [comment]
Thanks for being so helpful as to bring these latest issues to my attention. This color issue is resolved in v1.3.6.

**Comment by FeralFlora** [comment]
Can't check this, as I don't have any pending updates right now, but I trust that you've resolved it. No problem, it's just as helpful for me to have these issues resolved, especially with such responsiveness, so thanks to you too! It really gives me confidence to settle in with this theme long term.
