### ISSUE TITLE
Tag pills overlap in long tag lists inside callouts under Live preview and Reading, and elsewhere in Reading mode

### ISSUE THREAD

**Issue by FeralFlora** [callumhackett/obsidian_polka_theme#8]
See the screenshot:

### Inside a callout in Reading mode and Live preview. 
![image](https://user-images.githubusercontent.com/33608083/222411332-e95a33ea-349c-4e3c-ae93-842ad3d64136.png)

### In general text in Reading mode:
![image](https://user-images.githubusercontent.com/33608083/222412256-9f69fa8f-b8a7-4c1f-97e9-6b5d8a4bc52d.png)

### General text in Live preview, no overlap 👍 
![image](https://user-images.githubusercontent.com/33608083/222412450-e806a943-e865-4a4c-98f7-88e63f3a7fdd.png)

I have readable line length toggled on.

**Comment by callumhackett** [comment]
Fix available in v1.3.6. :)

**Comment by FeralFlora** [comment]
Fix works for me!

![image](https://user-images.githubusercontent.com/33608083/222569919-a196fdb5-f3b4-4ca4-a3a8-745709172b38.png)
